## Column Stores Tutorial

In this tutorial we will go over some queries and compare a column-oriented database management system (Clickhouse) with a row-oriented database management system (Postgres)

In [1]:
import pandas as pd
from sqlalchemy import create_engine, text

## Dataset

The dataset contain information related to credit card transactions being fraud or not, including timestamps, user identifiers, transaction amounts, locations, device types, and indicators of fraudulence, alongside demographic and financial attributes of users. Here's a brief description of each column:

- **timestamp**: Date and time when the transaction occurred.
- **user_id**: Unique identifier for the user associated with the transaction.
- **amount**: The monetary value of the transaction.
- **location**: Location where the transaction took place.
- **device_type**: Type of device used for the transaction (e.g., mobile, desktop).
- **is_fraud**: Binary indicator (0 or 1) specifying whether the transaction is flagged as fraudulent.
- **age**: Age of the user.
- **income**: Income level of the user.
- **debt**: Debt amount associated with the user.
- **credit_score**: Credit score of the user.

**Note:** If the file `data/credit_card_transaction.csv` is not found, you can download it from the following link and place it in the `data/` directory (relative to this notebook):

[Download credit_card_transaction.csv](https://drive.google.com/file/d/1JXkOKN2mnzVztKP7vmjiHyjC-YdEOm5n/view?usp=sharing)

In [2]:
df = pd.read_csv('data/credit_card_transaction.csv',nrows=500000)

In [3]:
df['timestamp'] = pd.to_datetime(df['timestamp']).dt.tz_localize('UTC')

In [4]:
df.head()

,timestamp,user_id,amount,location,device_type,is_fraud,age,income,debt,credit_score
0,2023-08-10 19:45:13+00:00,88e4edff-70ec-48e2-98fc-e2158bda39ce,2820.81,East Ginashire,Desktop,1,61,109941.13,26723.01,445
1,2023-04-24 18:48:52+00:00,d0b2cf73-ae9c-427a-b91b-154868254738,3074.92,Lake Michelehaven,Mobile,1,52,77270.96,4145.25,320
2,2023-09-11 22:09:37+00:00,53bcc7b9-4c8f-4c69-adf6-a6888431b7ba,176.97,West Sandrafurt,Desktop,0,26,127563.16,11420.89,397
3,2023-11-26 13:43:40+00:00,f623ca05-ec15-400d-b85d-9dcb99d6677e,3528.71,Randallbury,Desktop,1,47,124594.27,18794.04,819
4,2023-12-06 05:50:28+00:00,16d63788-6ef5-49ac-81f6-cda2e182043f,629.59,Port Casey,Desktop,0,19,139644.01,3172.29,573

In [5]:
df.shape

(500000, 10)

## Creating connection to Clickhouse and Postgres Server

In [6]:
clickhouse_connection_string = 'clickhouse://admin:click@clickhouse:8123/default'
postgres_connection_string = 'postgresql://admin:password@postgres:5432/clickhouse_pg_db'

In [7]:
clickhouse_engine = create_engine(clickhouse_connection_string)
postgres_engine = create_engine(postgres_connection_string)

## Loading data to Clickhouse and Postgres
The following code cells insert the data into a Clickhouse database

In [8]:
def insert_dataframe_to_clickhouse(df, table_name):
    
    # Truncate the table first
    truncate_query = f'TRUNCATE TABLE IF EXISTS {table_name}'
    client.execute(truncate_query)
    
    # Convert DataFrame to a list of tuples
    data = [tuple(x) for x in df.to_records(index=False)]
    
    # Generate the INSERT query dynamically based on the DataFrame's columns
    columns = ', '.join(df.columns)
    query = f'INSERT INTO {table_name} ({columns}) VALUES'
    
    # Execute the query with the data
    client.execute(query, data)

In [9]:
from clickhouse_driver import Client

# Define ClickHouse connection parameters
clickhouse_connection_settings = {
    'host': 'clickhouse',
    'port': 9000,
    'user': 'default',
    'password': '',
}

# Initialize ClickHouse client
client = Client(**clickhouse_connection_settings)

In [10]:
client.execute('DROP TABLE IF EXISTS transactions;')

create_table_query ='''CREATE TABLE transactions
(
    `timestamp` DateTime64(3), 
    `user_id` String,
    `amount` Float64,
    `location` String,
    `device_type` String,
    `is_fraud` Int64,
    `age` Int64,
    `income` Float64,
    `debt` Float64,
    `credit_score` Int64
) ENGINE = MergeTree()
PARTITION BY toYYYYMM(timestamp)  -- Partitioning by month
ORDER BY (timestamp, user_id);'''


# Execute create table query
client.execute(create_table_query)

[]

In [11]:
insert_dataframe_to_clickhouse(df, 'transactions')

We now insert our data into a Postgres database

In [12]:
from sqlalchemy import Table, Column, Integer, String, Float, DateTime,MetaData
from sqlalchemy.dialects.postgresql import TIMESTAMP

metadata = MetaData()
metadata.create_all(postgres_engine)

We are now ready to create a Postgres and Clickhouse session so that we can query both databases

In [13]:
import time
from sqlalchemy import create_engine
from clickhouse_sqlalchemy import make_session
from sqlalchemy.orm import sessionmaker

# PostgreSQL connection
PostgresSession = sessionmaker(bind=postgres_engine)
postgres_session = PostgresSession()

# ClickHouse connection
clickhouse_session = make_session(clickhouse_engine)

The following Python code snippet is used for defining a table schema in a SQL database using SQLAlchemy (a popular SQL toolkit library for Python). We are creating an empty table called "transactions"

In [14]:
transactions_table = Table('transactions', metadata,
    Column('timestamp', TIMESTAMP(timezone=True)),  # Assuming timezone-aware datetime
    Column('user_id', String),
    Column('amount', Float),
    Column('location', String),
    Column('device_type', String),
    Column('is_fraud', Integer),
    Column('age', Integer),
    Column('income', Float),
    Column('debt', Float),
    Column('credit_score', Integer)
)

In [15]:

# insert the new DataFrame into the empty table
df.to_sql('transactions', con=postgres_engine, if_exists='fail', index=False)

1000

## Functions for running the queries and comparing runtime between Clickhouse and Postgres

To run the query in clickhouse you can use the following code

In [16]:
def run_query(query):
    try:

        # Establish a connection
        with clickhouse_engine.connect() as connection:
            # Define the search query with SQLAlchemy's text construct
            # query = text(query)

            # Execute the search query
            result = connection.execute(query)

            # Fetch the result and convert it to a DataFrame
            clickhouse_df = pd.DataFrame(result.fetchall(), columns=result.keys())
            # print("Data from ClickHouse:")
            # print(clickhouse_df)
            return clickhouse_df

    except Exception as e:
        print("Query execution for ClickHouse failed:", e)
        return

To compare the runtime of postgres and clickhouse queries.

In [17]:
import time
from sqlalchemy import text

def compare_query_runtime(query):

    # Execute and time the PostgreSQL query
    try:
        start_time = time.time()
        result_postgres = postgres_session.execute(query).fetchall()
        end_time = time.time()
        postgres_duration = end_time - start_time
        print("PostgreSQL Query Time:", postgres_duration, "seconds")

    except Exception as e:
        print(f"An error occurred: {e}")
        
        
    # Execute and time the ClickHouse query
    try:
        start_time = time.time()
        clickhouse_session.execute(query).fetchall()
        clickhouse_duration = time.time() - start_time
        print("ClickHouse Query Time:", clickhouse_duration, "seconds")
    except Exception as e:
        print(f"ClickHouse error occurred: {e}")

## Example queries

Query to calculate the total number of transactions and the average transaction amount from the transactions dataset.

In [18]:
query = text('''SELECT
    COUNT(*) AS total_transactions,
    AVG(amount) AS average_transaction_amount
FROM transactions;
''')

q0 = run_query(query)

q0

   total_transactions  average_transaction_amount
0              500000                 1751.049186

In [19]:
compare_query_runtime(query)

PostgreSQL Query Time: 0.02036762237548828 seconds
ClickHouse Query Time: 0.00669550895690918 seconds


### Calculating the total amount of money involved in transactions for every age group, separating the sums into fraudulent and non-fraudulent transactions

In [20]:
# Example usage (assuming postgres_session and clickhouse_session are already set up)
query = text('''SELECT
    age,
    is_fraud,
    SUM(amount) AS total_amount
FROM transactions
GROUP BY age, is_fraud
''')

q1 = run_query(query)

q1

     age  is_fraud  total_amount
0     51         1   14094112.08
1     59         0    2349247.22
2     68         0    2351985.54
3     57         0    2358556.77
4     49         1   13802543.56
..   ...       ...           ...
101   56         0    2345994.63
102   48         1   14235830.59
103   69         0    2249963.18
104   58         0    2366527.15
105   50         1   14159877.02

[106 rows x 3 columns]

In [21]:
compare_query_runtime(query)

PostgreSQL Query Time: 0.05715513229370117 seconds
ClickHouse Query Time: 0.010226726531982422 seconds

### Query to find out the total number of transactions and the percentage of those transactions that are fraudulent, grouped by each type of device used for the transaction, and order the results by the percentage of fraud in descending order.

In [22]:
query = text('''SELECT
    device_type,
    COUNT(*) AS total_transactions,
    ROUND((SUM(is_fraud) / COUNT(*)) * 100, 2) AS fraud_percentage
FROM transactions
GROUP BY device_type
ORDER BY fraud_percentage DESC;

''')

q2 = run_query(query)

q2

  device_type  total_transactions  fraud_percentage
0     Desktop              167280             50.11
1      Tablet              166826             50.00
2      Mobile              165894             49.89

In [23]:
compare_query_runtime(query)

PostgreSQL Query Time: 0.030826091766357422 seconds
ClickHouse Query Time: 0.009525775909423828 seconds

### Query to calculate the percentage of fraudulent transactions for each month of each year, and order the results by year and month.

In [24]:
query = text('''SELECT
    EXTRACT(YEAR FROM timestamp) AS year,
    EXTRACT(MONTH FROM timestamp) AS month,
    ROUND(
        (SUM(CASE WHEN is_fraud = 1 THEN 1 ELSE 0 END) * 100.0) / COUNT(*),
        2
    ) AS fraud_percentage
FROM transactions
GROUP BY year, month
ORDER BY year, month;


''')
q3 = run_query(query)

q3

    year  month  fraud_percentage
0   2023      3             50.02
1   2023      4             49.42
2   2023      5             49.83
3   2023      6             50.12
4   2023      7             49.93
5   2023      8             50.23
6   2023      9             50.04
7   2023     10             50.22
8   2023     11             49.98
9   2023     12             50.24
10  2024      1             50.07
11  2024      2             49.88

In [25]:
compare_query_runtime(query)

PostgreSQL Query Time: 0.07088637351989746 seconds
ClickHouse Query Time: 0.01405644416809082 seconds

### Query to count the number of fraudulent transactions within specific income brackets: 'Low' for incomes of 50k or less, 'Medium' for incomes between 50k and 100k, and 'High' for incomes above 100k.

In [26]:
query = text('''SELECT
    CASE 
        WHEN income <= 50000 THEN 'Low'
        WHEN income > 50000 AND income <= 100000 THEN 'Medium'
        ELSE 'High' END AS income_bracket,
    COUNT(*) AS fraud_transactions_count
FROM transactions
WHERE is_fraud = 1
GROUP BY income_bracket
ORDER BY fraud_transactions_count DESC;

''')
q4 = run_query(query)

q4

  income_bracket  fraud_transactions_count
0           High                     96277
1         Medium                     95767
2            Low                     57965

In [27]:
compare_query_runtime(query)

PostgreSQL Query Time: 0.027334928512573242 seconds
ClickHouse Query Time: 0.008234977722167969 seconds

### Query to find the top 10 locations with the highest average transaction amount for non-fraudulent transactions. For these locations, what are the average income and average credit score of the individuals involved?

In [28]:
query = text('''SELECT
    location,
    AVG(income) AS average_income,
    AVG(amount) AS average_transaction_amount,
    AVG(credit_score) AS average_credit_score
FROM transactions
WHERE is_fraud = 0
GROUP BY location
ORDER BY average_transaction_amount DESC
LIMIT 10;


''')
q5 = run_query(query)

q5

,location,average_income,average_transaction_amount,average_credit_score
0,Bonillaville,149081.60,999.99,360.0
1,Port Tonyaside,117860.18,999.99,574.0
2,Lake Kayleemouth,142614.82,999.98,848.0
3,South Ebonyhaven,92282.58,999.87,792.0
4,Zoehaven,21920.32,999.78,600.0
5,North Angeltown,65876.34,999.58,594.0
6,Lake Kimberlystad,120325.29,999.57,444.0
7,South Walterfurt,98470.45,999.53,396.0
8,North Madisontown,112270.17,999.51,597.0
9,Lake Zacharyport,136435.82,999.46,563.0

In [29]:
compare_query_runtime(query)

PostgreSQL Query Time: 0.21113872528076172 seconds
ClickHouse Query Time: 0.027623891830444336 seconds

### Query to group transactions into age ranges (18-25, 26-40, 41-55, 56+), and for each age group, calculate the average transaction amount and the total number of transactions.

In [30]:
query = text('''SELECT
    is_fraud,
    CASE 
        WHEN age <= 25 THEN '18-25'
        WHEN age > 25 AND age <= 40 THEN '26-40'
        WHEN age > 40 AND age <= 55 THEN '41-55'
        ELSE '56+' END AS age_group,
    COUNT(*) AS total_transactions,
    SUM(amount) AS total_amount
FROM transactions
GROUP BY is_fraud, age_group
ORDER BY is_fraud, age_group;


''')
q6 = run_query(query)

q6

   is_fraud age_group  total_transactions  total_amount
0         0     18-25               37707  1.908756e+07
1         0     26-40               70721  3.564765e+07
2         0     41-55               71156  3.586882e+07
3         0       56+               70407  3.546175e+07
4         1     18-25               37644  1.129217e+08
5         1     26-40               70850  2.116944e+08
6         1     41-55               70781  2.128329e+08
7         1       56+               70734  2.120097e+08

In [31]:
compare_query_runtime(query)

PostgreSQL Query Time: 0.09114456176757812 seconds
ClickHouse Query Time: 0.01100921630859375 seconds

## Classifying Transactions as Fraudulent or Not

In [32]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, accuracy_score ,confusion_matrix, roc_auc_score

## Creating training dataset

1. It defines two Common Table Expressions (CTEs) named "Fraudulent" and "NonFraudulent":
   - **Fraudulent**: Selects records from the "transactions" table where the "is_fraud" column is equal to 1 (indicating fraudulent transactions). It also categorizes the transaction amount into three categories ('Low', 'Medium', 'High') based on predefined thresholds.
   - **NonFraudulent**: Selects records from the "transactions" table where the "is_fraud" column is equal to 0 (indicating non-fraudulent transactions). It categorizes the transaction amount into three categories ('Low', 'Medium', 'High') based on predefined thresholds.

2. Each CTE limits the number of selected records to 15,000.

3. The main query combines the results of the two CTEs using a UNION ALL operation, concatenating the rows from both CTEs into a single result set. This effectively creates a dataset that contains both fraudulent and non-fraudulent transactions, each categorized by transaction amount.

In [33]:
query = text('''WITH Fraudulent AS (
    SELECT *, 
           CASE
               WHEN amount < 1500 THEN 'Low'
               WHEN amount >= 1500 AND amount < 3500 THEN 'Medium'
               ELSE 'High'
           END AS transaction_amount_category
    FROM transactions
    WHERE is_fraud = 1
    LIMIT 15000
),
NonFraudulent AS (
    SELECT *, 
           CASE
               WHEN amount < 1500 THEN 'Low'
               WHEN amount >= 1500 AND amount < 3500 THEN 'Medium'
               ELSE 'High'
           END AS transaction_amount_category
    FROM transactions
    WHERE is_fraud = 0
    LIMIT 15000
)
SELECT * FROM Fraudulent
UNION ALL
SELECT * FROM NonFraudulent;

''')

data = run_query(query)

In [34]:
data.head()

,timestamp,user_id,amount,location,device_type,is_fraud,age,income,debt,credit_score,transaction_amount_category
0,2024-01-01 00:00:37,15f79570-6cf8-44d3-85ea-f01476e9b945,3409.52,Williamfort,Tablet,1,63,138953.41,19858.38,316,Medium
1,2024-01-01 00:01:58,04091db9-d82e-445c-8303-1d096554e5ec,2300.76,Lucasmouth,Mobile,1,54,28362.25,49233.64,308,Medium
2,2024-01-01 00:04:14,84e5c02c-a88e-4748-ba28-d000e6423f4b,4117.58,New Katie,Mobile,1,27,116996.99,47847.16,434,High
3,2024-01-01 00:07:03,acfb55b1-b115-4c47-b913-d34c13815d8c,1305.00,Mullinsmouth,Tablet,1,19,53014.70,36032.86,540,Low
4,2024-01-01 00:10:35,a0c4feba-af4c-4120-9ec3-a2cef54e11e5,2236.20,Diazland,Tablet,1,25,37912.72,17569.90,708,Medium

In [35]:
data.transaction_amount_category.value_counts()

transaction_amount_category
Low       16868
Medium     7555
High       5577
Name: count, dtype: int64

### Classification using Logistic Regression

We will use the Logistic Regression classifier to classify transactions into fraudulent or non-fraudulent. Refer to the comments in the code cells below that explain the different parts preparing the data to train the model

In [36]:
# Identify categorical columns
categorical_columns = ['location', 'device_type', 'transaction_amount_category']

# Apply one-hot encoding to categorical columns
data = pd.get_dummies(data, columns=categorical_columns)

# Split data into features and target variable
X = data.drop('is_fraud', axis=1)
y = data['is_fraud']

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [37]:
# Scale numerical features (example: standardization)
numerical_columns = ['age', 'income', 'debt', 'credit_score']
scaler = StandardScaler()
X_train[numerical_columns] = scaler.fit_transform(X_train[numerical_columns])
X_test[numerical_columns] = scaler.transform(X_test[numerical_columns])

In [38]:
# Exclude the 'timestamp' column from features
X_train = X_train.drop('timestamp', axis=1)
X_test = X_test.drop('timestamp', axis=1)

# Separate numeric and categorical columns
numeric_features = X_train.select_dtypes(include=['float64', 'int64']).columns
categorical_features = X_train.select_dtypes(include=['object']).columns

# Create transformers for numeric and categorical features
numeric_transformer = Pipeline(steps=[('numeric', StandardScaler())])  # You can replace StandardScaler with other scalers if needed
categorical_transformer = Pipeline(steps=[('onehot', OneHotEncoder(handle_unknown='ignore'))])

# Use ColumnTransformer to apply transformers to the respective columns
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numeric_features),
        ('cat', categorical_transformer, categorical_features)
    ])

In [39]:
# Append the classifier to the transformers in a pipeline
model = Pipeline(steps=[('preprocessor', preprocessor),
                        ('classifier', LogisticRegression(random_state=42))])

# Train the model
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

# Print the evaluation metrics
print(f"Accuracy: {accuracy:.2f}")
print("\nConfusion Matrix:\n", conf_matrix)
print("\nClassification Report:\n", classification_rep)

Accuracy: 0.99

Confusion Matrix:
 [[3034    0]
 [  61 2905]]

Classification Report:
               precision    recall  f1-score   support

           0       0.98      1.00      0.99      3034
           1       1.00      0.98      0.99      2966

    accuracy                           0.99      6000
   macro avg       0.99      0.99      0.99      6000
weighted avg       0.99      0.99      0.99      6000